name: Java CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Prepare application-secrets.properties (optional)
        if: ${{ secrets.APPLICATION_SECRETS_PROPERTIES_CONTENT != '' }}
        run: |
          mkdir -p ./backend/src/test/resources/
          echo "${{ secrets.APPLICATION_SECRETS_PROPERTIES_CONTENT }}" > ./backend/src/test/resources/application-secrets.properties

      - name: Build backend with Maven
        run: mvn clean install
        working-directory: ./backend

  build-microservice-notifications:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Prepare application-secrets.properties (optional)
        if: ${{ secrets.APPLICATION_SECRETS_PROPERTIES_CONTENT != '' }}
        run: |
          mkdir -p ./microservice-notifications/src/test/resources/
          echo "${{ secrets.APPLICATION_SECRETS_PROPERTIES_CONTENT }}" > ./microservice-notifications/src/test/resources/application-secrets.properties

      - name: Build microservice-notifications with Maven
        run: mvn clean install
        working-directory: ./microservice-notifications
